# numpy的练习

### 1.导入numpy

In [5]:
import numpy as np

### 2.打印numpy的版本和配置说明

In [8]:
print("numpy的版本"+np.__version__),np.show_config()  #

numpy的版本1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Lenovo/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows

(None, None)

### 3.创建一个长度为10的空向量

In [9]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4.如何找到一个数组的内存大小

In [18]:
z=np.zeros((10,10))
print(z.size*z.itemsize)
#itemsize是指一个数组的元素所占的长度（以字节表示），不同的数字类型有不同的长度（比如dtype中flot与complex的长度肯定不一样）（complex是复数类型，这个还未了解）

800


### 5.如何得到numpy中add函数的文档说明


In [20]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### 6.创建一个长度为10并且第五个值为1的向量空向量

In [21]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7.创建一个值域范围内从10到49的向量

In [22]:
z=np.arange(10,49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### 8.反转一个向量（从第一个元素变为最后一个元素）

In [26]:
z=np.arange(50)
z=z[::-1]    #这是时候将这个数组从后往前遍历
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 9.创建一个3*3的矩阵，然后从0~8

In [27]:
z=np.arange(9).reshape((3,3))
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10.找到数组【1,2,0,0,4,0】中非0元素的位置索引

In [30]:
a=[1,2,0,0,4,0]
nz=np.nonzero(a)   #nonzero是将非零的元素的索引返回，然后将数字类型搞出来
print(nz)

(array([0, 1, 4], dtype=int64),)


### 11.创建一个3*3的单位矩阵

In [32]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12.创建一个3\*3\*3的随机数组

In [56]:
#z=np.random.rand(3,3,3)   #方法一,这个方法的数据分布是正态的,所以可以存在正数和负数
z=np.random.random_sample((3,3,3))
print(z)

[[[0.91291667 0.36274164 0.61451336]
  [0.24283017 0.06392499 0.35616541]
  [0.12289106 0.26125955 0.3238554 ]]

 [[0.09317244 0.81623047 0.7915225 ]
  [0.19791003 0.89837287 0.97930985]
  [0.92253514 0.36964761 0.10355194]]

 [[0.84421861 0.67508491 0.82612711]
  [0.84730616 0.3968263  0.55067748]
  [0.55294443 0.71976364 0.98984747]]]


### 13.创建一个10*10的随机数组被找到它的最大和最小值

In [51]:
z=np.random.randn(3,3,3)
zmin,zmax=z.min(),z.max()
print("max_val and min_val is "+str(zmax)+","+str(zmin))

max_val and min_val is 1.7580132531917856,-1.6419861998120024


### 14.创建一个长度为30的随机向量并找到它的平均值

In [57]:
z=np.random.rand(30)  #对照上面，如果是某个维度上的数字大小，决定了这个维度上的长度
print("长度为30随机向量"+str(z))
val_mean=z.mean()
print(val_mean)

长度为30随机向量[0.11339796 0.6724967  0.60316419 0.39274108 0.9258309  0.98741098
 0.45330668 0.56752388 0.88817235 0.23290237 0.0824301  0.92453356
 0.40877794 0.1764265  0.13622203 0.18955565 0.36345388 0.79277672
 0.91413614 0.68797636 0.29481192 0.63686913 0.37721594 0.32859658
 0.51832552 0.60479491 0.21925442 0.86516548 0.13430814 0.7220529 ]
0.5071543634684257


### 15.创建一个二维数组，其中边界为1，其余值为0

In [74]:
z=np.ones((50,50))
z[1:-1:1,1:-1:1]=0    #list的遍历是中将最后一个数写为-1,但是最后取不到最后那个数，如果想取到最后那个数，我需要写为:
print(z)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


### 16.对于所存在的数组，如何添加一个用0填充的边界

In [81]:
np.info(np.pad)

 pad(array, pad_width, mode, **kwargs)

Pads an array.

Parameters
----------
array : array_like of rank N
    Input array
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function
    One of the following string values or a user supplied function.

    'constant'
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with the med

In [91]:
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0) #数字pad_width=1表示这个边界一层
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17.以下表达式运行结果分别是

In [102]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)
"""
和nan一样让人搞混的是None，None是python表示空缺的，nan是numpy个pandas表示空缺的。
其中None是python中特殊的数据类型。而nan是一个特殊的float。
通过float的特性就可以知道为什么上面会有这样的输出了。
"""

nan
False
False
nan
False


'\n和nan一样让人搞混的是None，None是python表示空缺的，nan是numpy个pandas表示空缺的。\n其中None是python中特殊的数据类型。而nan是一个特殊的float。\n通过float的特性就可以知道为什么上面会有这样的输出了。\n'

### 18.创建一个5\*5的矩阵，并设置1,2,3,4落在其对角线下方的位置

In [103]:
np.info(np.diag)

 diag(v, k=0)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> x = np.ar

In [107]:
z=np.diag(1+np.arange(4),k=-1)  #要注意arrange和array的区别，一个是创造一个数组，一个数让其成为一个数组。
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19.创建一个8\*8的矩阵，设置成棋盘样式

In [115]:
z=np.zeros((8,8))
z[1::2,0::2]=1
z[0::2,1::2]=1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 20.考虑一个（6,7,8）形状的数组，其中第100个元素的索引(x,y,z)是什么

In [118]:
np.info(np.unravel_index)

unravel_index(indices, shape, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``shape``. Before version 1.6.0,
    this function accepted just one index value.
shape : tuple of ints
    The shape of the array to use for unraveling ``indices``.

    .. versionchanged:: 1.16.0
        Renamed from ``dims`` to ``shape``.

order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1]))
>>> np.unravel_index([31, 41, 1

In [122]:
print(np.unravel_index(335,(6,7,8)))
"""
如果是填入的是形状(x,y,z)，那么找到的就是这个位置（第几个）
如果填入的是向量本身，那么找到的就是那个数字的位置
"""

(5, 6, 7)


'\n如果是填入的是形状(x,y,z)，那么找到的就是这个位置（第几个）\n如果填入的是向量本身，那么找到的就是那个数字的位置\n'

### 21.用tile函数创建一个8\*8

In [123]:
np.info(np.tile)

 tile(A, reps)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an array.
br

In [125]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))  #对于二维数组认识不够（上升到多维）
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22.对一个5\*5的随机矩阵do归一化处理

In [131]:
z=np.random.random((5,5))
zmin,zmax=z.min(),z.max()
z=(z-zmin)/(zmax-zmin)
print(z)

[[0.         0.2690359  0.11711002 0.28414194 0.18760951]
 [0.29324708 0.14923814 0.49894468 0.97028961 0.61387341]
 [1.         0.58690711 0.5560668  0.81078756 0.01311079]
 [0.82556837 0.57595787 0.31023049 0.75695907 0.35921332]
 [0.10756579 0.38785028 0.16580735 0.4527026  0.53666543]]


### 23.创建一个将颜色描述为(RGBA)四个无符号字节的自定义dytpe?

In [138]:
np.info(np.dtype)

 dtype()

dtype(obj, align=False, copy=False)

Create a data type object.

A numpy array is homogeneous, and contains elements described by a
dtype object. A dtype object can be constructed from different
combinations of fundamental numeric types.

Parameters
----------
obj
    Object to be converted to a data type object.
align : bool, optional
    Add padding to the fields to match what a C compiler would output
    for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
    or a comma-separated string. If a struct dtype is being created,
    this also sets a sticky alignment flag ``isalignedstruct``.
copy : bool, optional
    Make a new copy of the data-type object. If ``False``, the result
    may just be a reference to a built-in data-type object.

See also
--------
result_type

Examples
--------
Using array-scalar type:

>>> np.dtype(np.int16)
dtype('int16')

Structured type, one field name 'f1', containing int16:

>>> np.dtype([('f1', np.int16)])
dtype([('f1', '<i2

In [140]:
color=np.dtype([
    ("r",np.ubyte,1),
    ("g",np.ubyte,1),
    ("b",np.ubyte,1),
    ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### 24.一个5\*3的矩阵和一个3\*2的矩阵成绩是什么？

In [141]:
a=np.random.random((5,3))
b=np.random.random((3,2))
print(np.dot(a,b))

[[0.75975308 0.9070075 ]
 [0.43460422 0.13351039]
 [0.34079208 0.37160168]
 [0.49139479 0.2613268 ]
 [0.77517685 0.74729066]]


### 25.给定义一个一维数组，对其3到8之间所有元素取反

In [153]:
z=np.arange(11)
#z[(3<=z)&(z<7)]*=-1  #如何取一个区间的元素
z[3:8]*=-1           #这两个都可以
print(z)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


#  26.下面运行的结果是什么  

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
 ```

In [157]:
print(sum(range(5),-1))

10


In [158]:
from numpy import *
print(np.sum(range(5),-1))

10


### 27.下面哪一个是合法的

```
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [159]:
z=np.arange(11)
print(z)

[  0   1   4   9  16  25  36  49  64  81 100]


In [166]:
2<<z>>2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [167]:
z <-z

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [169]:
1j*z  #这是一个复数计算

array([0. +0.j, 0. +1.j, 0. +2.j, 0. +3.j, 0. +4.j, 0. +5.j, 0. +6.j,
       0. +7.j, 0. +8.j, 0. +9.j, 0.+10.j])

In [170]:
z/1/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [171]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()