# numpy的练习

### 1.导入numpy

In [1]:
import numpy as np

### 2.打印numpy的版本和配置说明

In [2]:
print("numpy的版本"+np.__version__),np.show_config()  #

numpy的版本1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Lenovo/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows

(None, None)

### 3.创建一个长度为10的空向量

In [3]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4.如何找到一个数组的内存大小

In [4]:
z=np.zeros((10,10))
print(z.size*z.itemsize)
#itemsize是指一个数组的元素所占的长度（以字节表示），不同的数字类型有不同的长度（比如dtype中flot与complex的长度肯定不一样）（complex是复数类型，这个还未了解）

800


### 5.如何得到numpy中add函数的文档说明


In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### 6.创建一个长度为10并且第五个值为1的向量空向量

In [6]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7.创建一个值域范围内从10到49的向量

In [7]:
z=np.arange(10,49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### 8.反转一个向量（从第一个元素变为最后一个元素）

In [8]:
z=np.arange(50)
z=z[::-1]    #这是时候将这个数组从后往前遍历
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 9.创建一个3*3的矩阵，然后从0~8

In [9]:
z=np.arange(9).reshape((3,3))
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10.找到数组【1,2,0,0,4,0】中非0元素的位置索引

In [10]:
a=[1,2,0,0,4,0]
nz=np.nonzero(a)   #nonzero是将非零的元素的索引返回，然后将数字类型搞出来
print(nz)

(array([0, 1, 4], dtype=int64),)


### 11.创建一个3*3的单位矩阵

In [11]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12.创建一个3\*3\*3的随机数组

In [12]:
#z=np.random.rand(3,3,3)   #方法一,这个方法的数据分布是正态的,所以可以存在正数和负数
z=np.random.random_sample((3,3,3))
print(z)

[[[0.86612843 0.27927953 0.85901358]
  [0.04581943 0.10994034 0.04886274]
  [0.91918765 0.50674987 0.7196552 ]]

 [[0.61154154 0.60158606 0.1662134 ]
  [0.71970573 0.42752862 0.36491446]
  [0.88457949 0.41324857 0.81300708]]

 [[0.45416754 0.90590386 0.0113495 ]
  [0.28714156 0.19951672 0.22154397]
  [0.57890405 0.85182399 0.05348335]]]


### 13.创建一个10*10的随机数组被找到它的最大和最小值

In [13]:
z=np.random.randn(3,3,3)
zmin,zmax=z.min(),z.max()
print("max_val and min_val is "+str(zmax)+","+str(zmin))

max_val and min_val is 2.3758813210318666,-3.93836142305252


### 14.创建一个长度为30的随机向量并找到它的平均值

In [14]:
z=np.random.rand(30)  #对照上面，如果是某个维度上的数字大小，决定了这个维度上的长度
print("长度为30随机向量"+str(z))
val_mean=z.mean()
print(val_mean)

长度为30随机向量[0.97043332 0.1426573  0.43110015 0.67326047 0.69737101 0.83187045
 0.48216339 0.70184579 0.37340126 0.13457425 0.89729992 0.82977751
 0.92182434 0.44531325 0.71308669 0.90658184 0.85044903 0.96921646
 0.87683911 0.24250146 0.4519146  0.10370196 0.18533915 0.64586479
 0.60278101 0.82041718 0.98580246 0.96968937 0.42063727 0.88944033]
0.6389051716793326


### 15.创建一个二维数组，其中边界为1，其余值为0

In [15]:
z=np.ones((50,50))
z[1:-1:1,1:-1:1]=0    #list的遍历是中将最后一个数写为-1,但是最后取不到最后那个数，如果想取到最后那个数，我需要写为:
print(z)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


### 16.对于所存在的数组，如何添加一个用0填充的边界

In [16]:
np.info(np.pad)

 pad(array, pad_width, mode, **kwargs)

Pads an array.

Parameters
----------
array : array_like of rank N
    Input array
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function
    One of the following string values or a user supplied function.

    'constant'
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with the med

In [17]:
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0) #数字pad_width=1表示这个边界一层
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17.以下表达式运行结果分别是

In [18]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)
"""
和nan一样让人搞混的是None，None是python表示空缺的，nan是numpy个pandas表示空缺的。
其中None是python中特殊的数据类型。而nan是一个特殊的float。
通过float的特性就可以知道为什么上面会有这样的输出了。
"""

nan
False
False
nan
False


'\n和nan一样让人搞混的是None，None是python表示空缺的，nan是numpy个pandas表示空缺的。\n其中None是python中特殊的数据类型。而nan是一个特殊的float。\n通过float的特性就可以知道为什么上面会有这样的输出了。\n'

### 18.创建一个5\*5的矩阵，并设置1,2,3,4落在其对角线下方的位置

In [19]:
np.info(np.diag)

 diag(v, k=0)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> x = np.ar

In [20]:
z=np.diag(1+np.arange(4),k=-1)  #要注意arrange和array的区别，一个是创造一个数组，一个数让其成为一个数组。
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19.创建一个8\*8的矩阵，设置成棋盘样式

In [21]:
z=np.zeros((8,8))
z[1::2,0::2]=1
z[0::2,1::2]=1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 20.考虑一个（6,7,8）形状的数组，其中第100个元素的索引(x,y,z)是什么

In [22]:
np.info(np.unravel_index)

unravel_index(indices, shape, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``shape``. Before version 1.6.0,
    this function accepted just one index value.
shape : tuple of ints
    The shape of the array to use for unraveling ``indices``.

    .. versionchanged:: 1.16.0
        Renamed from ``dims`` to ``shape``.

order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1]))
>>> np.unravel_index([31, 41, 1

In [23]:
print(np.unravel_index(335,(6,7,8)))
"""
如果是填入的是形状(x,y,z)，那么找到的就是这个位置（第几个）
如果填入的是向量本身，那么找到的就是那个数字的位置
"""

(5, 6, 7)


'\n如果是填入的是形状(x,y,z)，那么找到的就是这个位置（第几个）\n如果填入的是向量本身，那么找到的就是那个数字的位置\n'

### 21.用tile函数创建一个8\*8

In [24]:
np.info(np.tile)

 tile(A, reps)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an array.
br

In [25]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))  #对于二维数组认识不够（上升到多维）
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22.对一个5\*5的随机矩阵do归一化处理

In [26]:
z=np.random.random((5,5))
zmin,zmax=z.min(),z.max()
z=(z-zmin)/(zmax-zmin)
print(z)

[[0.06596405 0.02650148 0.20830155 0.16612644 0.38930432]
 [0.59044729 0.52977723 0.98350297 1.         0.07980521]
 [0.43356578 0.77410151 0.55367506 0.66307029 0.05834622]
 [0.96438135 0.91415557 0.69113206 0.7026853  0.81362295]
 [0.86391552 0.47656858 0.9964541  0.08129851 0.        ]]


### 23.创建一个将颜色描述为(RGBA)四个无符号字节的自定义dytpe?

In [27]:
np.info(np.dtype)

 dtype()

dtype(obj, align=False, copy=False)

Create a data type object.

A numpy array is homogeneous, and contains elements described by a
dtype object. A dtype object can be constructed from different
combinations of fundamental numeric types.

Parameters
----------
obj
    Object to be converted to a data type object.
align : bool, optional
    Add padding to the fields to match what a C compiler would output
    for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
    or a comma-separated string. If a struct dtype is being created,
    this also sets a sticky alignment flag ``isalignedstruct``.
copy : bool, optional
    Make a new copy of the data-type object. If ``False``, the result
    may just be a reference to a built-in data-type object.

See also
--------
result_type

Examples
--------
Using array-scalar type:

>>> np.dtype(np.int16)
dtype('int16')

Structured type, one field name 'f1', containing int16:

>>> np.dtype([('f1', np.int16)])
dtype([('f1', '<i2

In [28]:
color=np.dtype([
    ("r",np.ubyte,1),
    ("g",np.ubyte,1),
    ("b",np.ubyte,1),
    ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### 24.一个5\*3的矩阵和一个3\*2的矩阵成绩是什么？

In [29]:
a=np.random.random((5,3))
b=np.random.random((3,2))
print(np.dot(a,b))

[[0.55106516 0.86494718]
 [0.39318007 0.50528256]
 [0.31502329 0.56974601]
 [0.32360231 0.59167265]
 [0.34809017 0.35377307]]


### 25.给定义一个一维数组，对其3到8之间所有元素取反

In [30]:
z=np.arange(11)
#z[(3<=z)&(z<7)]*=-1  #如何取一个区间的元素
z[3:8]*=-1           #这两个都可以
print(z)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


#  26.下面运行的结果是什么  

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
 ```

In [31]:
print(sum(range(5),-1))

9


In [32]:
from numpy import *
print(np.sum(range(5),-1))

10


### 27.下面哪一个是合法的

```
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [33]:
z=np.arange(11)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [34]:
2<<z>>2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [35]:
z <-z

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [36]:
1j*z  #这是一个复数计算

array([0. +0.j, 0. +1.j, 0. +2.j, 0. +3.j, 0. +4.j, 0. +5.j, 0. +6.j,
       0. +7.j, 0. +8.j, 0. +9.j, 0.+10.j])

In [37]:
z/1/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

###  28.下面结果分别是什么

```python
np.array(0)/np.arry(0)
np.array(0)//np.array(0)
np.array([np.nan])
```

In [39]:
np.array(0) / np.array(0)

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [40]:
np.array(0) // np.array(0)  #//整除

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [43]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

### 29.如何找到两个数组的共同元素

In [46]:
np.info(np.random.randint)

randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

Parameters
----------
low : int
    Lowest (signed) integer to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. All dtypes are determined by their
    name, i.e., 'int64', 'int'

In [51]:
z1=np.random.randint(0,10,10)   #randint（）连续三个数字的目的是：一个是最小值，一个是最大值，另一是产生多少个这样的随机数
z2=np.random.randint(0,10,9)
print(np.intersect1d(z1,z2))

[0 3 4 7 8]


### 30.如何从零位对浮点数组做舍入 （以0为中心从外扩张）

In [53]:
np.info(np.random.uniform)

uniform(low=0.0, high=1.0, size=None)

Draw samples from a uniform distribution.

Samples are uniformly distributed over the half-open interval
``[low, high)`` (includes low, but excludes high).  In other words,
any value within the given interval is equally likely to be drawn
by `uniform`.

Parameters
----------
low : float or array_like of floats, optional
    Lower boundary of the output interval.  All values generated will be
    greater than or equal to low.  The default value is 0.
high : float or array_like of floats
    Upper boundary of the output interval.  All values generated will be
    less than high.  The default value is 1.0.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single value is returned if ``low`` and ``high`` are both scalars.
    Otherwise, ``np.broadcast(low, high).size`` samples are drawn.

Returns
-------
out : ndarray or s

In [56]:
print(np.random.uniform(-10,10,100))  #uiniform()可以产生随机的浮点数，括号的意思分别为：最低的数，最大的数，总共有几个

[-4.30757839  6.69825004 -9.1825824   1.95793068 -1.71453063  3.00668216
  9.1909848   9.45586913  3.18780094 -8.92767932  2.93120105 -7.64074336
  2.0669778  -5.90470917 -6.50477395  6.63317106  2.89118823  8.75296391
  2.98644425 -2.9448262  -9.87659576  2.4767507  -6.68602027  0.63132453
 -5.22810382  7.57044183  5.77703671  2.37910487 -1.54407867 -7.46341356
 -7.57899848  8.58637626 -0.11120976 -4.76345202  9.27102791 -7.3291658
  1.13303534 -5.89630386 -2.28380378  2.39034983 -3.04134391  5.12405506
  2.12007652  2.04811262 -4.12900292  3.0552595   4.80258295  8.39662575
  2.64806043  3.50857256 -5.91038505  8.64867122 -8.56335161 -6.93885162
  2.73374573 -0.35655298 -8.44828326 -8.04620712  8.36566684 -8.72457975
 -7.40089534  3.74738446 -3.76372222 -9.35991366  4.78280402  5.53619552
  1.27282767 -3.16527434 -5.52169015 -5.87496072  2.01441479  9.11946175
  2.61792591  7.59765084  1.24468922 -8.58143761  6.38341604 -7.24109393
 -9.989116   -1.87117818  5.24980073  0.08409206  6.

In [58]:
np.info(np.ceil)  #返回输出的上限

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

In [60]:
np.info(np.copysign)  #将x1的符号改为x2的符号

copysign(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Change the sign of x1 to that of x2, element-wise.

If both arguments are arrays or sequences, they have to be of the same
length. If `x2` is a scalar, its sign will be copied to all elements of
`x1`.

Parameters
----------
x1 : array_like
    Values to change the sign of.
x2 : array_like
    The sign of `x2` is copied to `x1`.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only

In [62]:
z=np.random.uniform(-10,10,100)
print(np.copysign(np.ceil(np.abs(z)),z))  #逻辑是，先变为绝对值，然后取上边界的整数，再对应的地方加负号

[  5.   3.   4.   3.   5. -10.  -1.   6.  -4.   2.  10.   6.  -2.  -9.
  -2.   4.  -4.  -2.  -1. -10.   8.   1.  -5.   8.  -5.  -4.   5.  -8.
  10. -10.  -2.   1.  -3.   8.  -9.  -3.  -1.   4.   1.   5.  -8.   4.
   3.   5.  -4.   7.  -2.   6. -10.  -6.   9.   1.   1.  -2.  -1. -10.
   3.   3.   5.   4.   3.   5.  -2.  -2.  -3.  -4.  -3.   4.  -3.  -3.
  -2.  -3.   9.   3.   7.   7.  -6.  -6.  -7.  -4.   6.  10.  -2.   5.
   7.   7. -10.  10.   9.   8.  -7.  -3.   7.  -9.  10.  -6.   3.  -9.
   6.   3.]


### 31.忽略numpy的所有警告


In [64]:
#suicide mode on 
defaults=np.seterr(all="ignore")
z = np.ones(1)/0
    

In [68]:
#back to sanity
_=np.seterr(**defaults)
z=np.ones(1) / 0

In [75]:
#An equivalent way, with a context manager:
with np.errstate(divide='ignore'): #除法的方面可以忽略
    z = np.ones(1)/0

### 32.下面的表达式正确吗

In [76]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [77]:
np.emath.sqrt(-1)  #说明这个可以将数据的大小扩展到复数域

1j

### 33.如何得到与2016年7月对应的日期

In [79]:
z = np.arange('2016-07','2017-08',dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31' '2016-08-01' '2016-08-02' '2016-08-03' '2016-08-04'
 '2016-08-05' '2016-08-06' '2016-08-07' '2016-08-08' '2016-08-09'
 '2016-08-10' '2016-08-11' '2016-08-12' '2016-08-13' '2016-08-14'
 '2016-08-15' '2016-08-16' '2016-08-17' '2016-08-18' '2016-08-19'
 '2016-08-20' '2016-08-21' '2016-08-22' '2016-08-23' '2016-08-24'
 '2016-08-25' '2016-08-26' '2016-08-27' '2016-08-28' '2016-08-29'
 '2016-08-30' '2016-08-31' '2016-09-01' '2016-09-02' '2016-09-03'
 '2016-09-04' '2016-09-05' '2016-09-06' '2016-09-07' '2016-09-08'
 '2016-09-09' '2016-09-10' '2016-09-11' '2016-09-12' '2016-09-13'
 '2016-09-


### 34.如何的到昨天，今天，明天的日期

In [84]:
np.info(np.datetime64)

 datetime64()

Base class for numpy scalar types.

Class from which most (all?) numpy scalar types are derived.  For
consistency, exposes the same API as `ndarray`, despite many
consequent attributes being either "get-only," or completely irrelevant.
This is the class from which it is strongly suggested users should derive
custom scalar types.


Methods:

  all  --  Not implemented (virtual attribute)
  any  --  Not implemented (virtual attribute)
  argmax  --  Not implemented (virtual attribute)
  argmin  --  Not implemented (virtual attribute)
  argsort  --  Not implemented (virtual attribute)
  astype  --  Not implemented (virtual attribute)
  byteswap  --  Not implemented (virtual attribute)
  choose  --  Not implemented (virtual attribute)
  clip  --  Not implemented (virtual attribute)
  compress  --  Not implemented (virtual attribute)
  conj  --  None
  conjugate  --  Not implemented (virtual attribute)
  copy  --  Not implemented (virtual attribute)
  cumprod  --  Not implemen

In [101]:
today=np.datetime64('today','D')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')
print("今天"+str(np.datetime64('today','D')))
print("昨天"+" "+str(yesterday))
print("明天"+" "+str(tomorrow))
"""
D，Y,M是显示的日，年，月的简写
timedelta是显示出了这个日子，如上面的写的就是一天（1，'Y'）就是一个月

"""

今天2019-06-23
昨天 2019-06-22
明天 2019-06-24


"\nD，Y,M是显示的日，年，月的简写\ntimedelta是显示出了这个日子，如上面的写的就是一天（1，'Y'）就是一个月\n\n"

###  35.如何直接在位计算(A+B)\*(-A/2)

In [146]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [145]:
a = ones(4).reshape((2,2))*2
print(a)
b=np.ones(4).reshape((2,2))*3
print(b)
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
print(a)
"""
注意两点：1.如果是直接的维度不相同的运算，只要保证列数相同，那么add，divide以及multiply的运算都可以完成
2.如果是运用out的输出，你输出的那个矩阵是和运算结果维度相同
"""

[[2. 2.]
 [2. 2.]]
[[3. 3.]
 [3. 3.]]
[[-5. -5.]
 [-5. -5.]]


'\n注意两点：1.如果是直接的维度不相同的运算，只要保证列数相同，那么add，divide以及multiply的运算都可以完成\n2.如果是运用out的输出，你输出的那个矩阵是和运算结果维度相同\n'

###  36.用五种不同的方法去提取一个随机数组的整数部分

In [150]:
z = np.random.uniform(0,10,19)
print(np,ceil(z)-1)   #ceil是向上取整

<module 'numpy' from 'C:\\Users\\Lenovo\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'> [0. 9. 3. 4. 3. 3. 4. 5. 6. 7. 5. 4. 2. 6. 8. 8. 8. 8. 9.]


In [153]:
print(np.floor(z)) #floor是向下取整

[0. 9. 3. 4. 3. 3. 4. 5. 6. 7. 5. 4. 2. 6. 8. 8. 8. 8. 9.]


In [154]:
print(z.astype(int))

[0 9 3 4 3 3 4 5 6 7 5 4 2 6 8 8 8 8 9]


In [155]:
np.info(np.trunc)

trunc(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the truncated value of the input, element-wise.

The truncated value of the scalar `x` is the nearest integer `i` which
is closer to zero than `x` is. In short, the fractional part of the
signed number `x` is discarded.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`

In [157]:
print(np.trunc(z))   #将数的小数部分切去

[0. 9. 3. 4. 3. 3. 4. 5. 6. 7. 5. 4. 2. 6. 8. 8. 8. 8. 9.]


In [159]:
print(z-z%1)    #逻辑在于小数点的余数是小数部分，所以减去就是整数。

[0. 9. 3. 4. 3. 3. 4. 5. 6. 7. 5. 4. 2. 6. 8. 8. 8. 8. 9.]


### 37.创建一个5\*5的矩阵，其中每行的范围是0~4

In [162]:
z = np.zeros((5,5))
a = np.arange(5)
z=np.add(z,a)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38.考虑通过生产函数，生产10个int的数组

In [163]:
np.info(np.fromiter)

fromiter(iterable, dtype, count=-1)

Create a new 1-dimensional array from an iterable object.

Parameters
----------
iterable : iterable object
    An iterable object providing data for the array.
dtype : data-type
    The data-type of the returned array.
count : int, optional
    The number of items to read from *iterable*.  The default is -1,
    which means all data is read.

Returns
-------
out : ndarray
    The output array.

Notes
-----
Specify `count` to improve performance.  It allows ``fromiter`` to
pre-allocate the output array, instead of resizing it on demand.

Examples
--------
>>> iterable = (x*x for x in range(5))
>>> np.fromiter(iterable, float)
array([  0.,   1.,   4.,   9.,  16.])


In [166]:
def generate():
    for i in range(10):
        yield i    #https://www.ibm.com/developerworks/cn/opensource/os-cn-python-yield/index.html
z=np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39.创建一个长度为10的随机向量，其值范围是0~1，但是不包括0和1

In [167]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
          axis=0)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples

In [171]:
z  = np.linspace(0,1,11,endpoint=False)[1:] #linspace不能算是真的随机，它的区间是评价的
print((z[4]-z[3])==(z[8]-z[7]))
print(z)

True
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [173]:
#方法二
z = np.random.uniform(0,1,10)   
print(z)

[0.96823777 0.93877655 0.75100752 0.81343396 0.72466366 0.59505106
 0.50347825 0.06564359 0.38056624 0.92216958]


### 40.创建一个长度为10的随机向量，并将其排序

In [178]:
z = np.random.uniform(1,299,10)
z.sort()
print(z)

[ 79.88115187  94.23284178 117.53832209 127.57658739 151.59593651
 170.62233243 175.5858285  234.2893042  254.15941973 269.93383711]


### 41.对于小数组，如何用np.sum()更快的方法对其求和

In [179]:
np.info(np.add.reduce)

reduce(a, axis=0, dtype=None, out=None, keepdims=False, initial)

Reduces `a`'s dimension by one, by applying ufunc along one axis.

Let :math:`a.shape = (N_0, ..., N_i, ..., N_{M-1})`.  Then
:math:`ufunc.reduce(a, axis=i)[k_0, ..,k_{i-1}, k_{i+1}, .., k_{M-1}]` =
the result of iterating `j` over :math:`range(N_i)`, cumulatively applying
ufunc to each :math:`a[k_0, ..,k_{i-1}, j, k_{i+1}, .., k_{M-1}]`.
For a one-dimensional array, reduce produces results equivalent to:
::

 r = op.identity # op = ufunc
 for i in range(len(A)):
   r = op(r, A[i])
 return r

For example, add.reduce() is equivalent to sum().

Parameters
----------
a : array_like
    The array to act on.
axis : None or int or tuple of ints, optional
    Axis or axes along which a reduction is performed.
    The default (`axis` = 0) is perform a reduction over the first
    dimension of the input array. `axis` may be negative, in
    which case it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If

使用np.add.reduce。和np.add()比起来两者的性能似乎完全不同：对于相对较小的阵列大小，add.reduce大约快两倍。

In [180]:
z = np.arange(10)
print(np.add.reduce(z))


45


### 42.对于两个随机的数组，检查他们是否相等

In [181]:
np.info(np.allclose)

 allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)

Returns True if two arrays are element-wise equal within a tolerance.

The tolerance values are positive, typically very small numbers.  The
relative difference (`rtol` * abs(`b`)) and the absolute difference
`atol` are added together to compare against the absolute difference
between `a` and `b`.

If either array contains one or more NaNs, False is returned.
Infs are treated as equal if they are in the same place and of the same
sign in both arrays.

Parameters
----------
a, b : array_like
    Input arrays to compare.
rtol : float
    The relative tolerance parameter (see Notes).
atol : float
    The absolute tolerance parameter (see Notes).
equal_nan : bool
    Whether to compare NaN's as equal.  If True, NaN's in `a` will be
    considered equal to NaN's in `b` in the output array.

    .. versionadded:: 1.10.0

Returns
-------
allclose : bool
    Returns True if the two arrays are equal within the given
    tolerance; False 

In [182]:
np.info(np.array_equal)

 array_equal(a1, a2)

True if two arrays have the same shape and elements, False otherwise.

Parameters
----------
a1, a2 : array_like
    Input arrays.

Returns
-------
b : bool
    Returns True if the arrays are equal.

See Also
--------
allclose: Returns True if two arrays are element-wise equal within a
          tolerance.
array_equiv: Returns True if input arrays are shape consistent and all
             elements equal.

Examples
--------
>>> np.array_equal([1, 2], [1, 2])
True
>>> np.array_equal(np.array([1, 2]), np.array([1, 2]))
True
>>> np.array_equal([1, 2], [1, 2, 3])
False
>>> np.array_equal([1, 2], [1, 4])
False


In [184]:
a = np.random.uniform(1,10,10)
b = np.random.uniform(1,10,10)
print(np.array_equal(a,b))
print((np.allclose(a,b)))

False
False


### 43.创建一个只读数组

In [189]:
z=ones(10).reshape((2,5))
z.flags.writeable = False

In [190]:
z[0]=1

ValueError: assignment destination is read-only

### 44.笛卡尔坐标系下的一个10\*2的矩阵转换为极坐标系

In [194]:
z = np.random.random((10,2))
x,y  = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
T = np.arctan2(y,x)
print(r)
print(T)

[1.0574407  1.20329312 0.2076386  0.89496139 1.01047294 0.83366176
 0.90329972 0.98709327 0.7407205  0.58964518]
[1.1208307  0.96505929 0.81983175 0.28435031 1.35024838 1.39748686
 0.60886802 1.18371731 0.82804943 0.99926003]


### 45.创建一个长度为10的向量，并将向量的最大值设为1

In [195]:
np.info(np.argmax)

 argmax(a, axis=None, out=None)

Returns the indices of the maximum values along an axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    By default, the index is into the flattened array, otherwise
    along the specified axis.
out : array, optional
    If provided, the result will be inserted into this array. It should
    be of the appropriate shape and dtype.

Returns
-------
index_array : ndarray of ints
    Array of indices into the array. It has the same shape as `a.shape`
    with the dimension along `axis` removed.

See Also
--------
ndarray.argmax, argmin
amax : The maximum value along a given axis.
unravel_index : Convert a flat index into an index tuple.

Notes
-----
In case of multiple occurrences of the maximum values, the indices
corresponding to the first occurrence are returned.

Examples
--------
>>> a = np.arange(6).reshape(2,3) + 10
>>> a
array([[10, 11, 12],
       [13, 14, 15]])
>>> np.argmax(a)
5
>>> np.argmax(a, axis=0)
array([1, 

In [198]:
z = np.random.uniform(1,80,9)
z[np.argmax(z)]=1
print(z)

[41.32920529  4.84285881 75.42208268 49.44904989  1.         72.00432805
 72.51321305  7.55494584 53.71283899]


### 46.创建一个结构化数组，并实现x和y坐标覆盖[0,1]x[0,1]区域

In [199]:
np.info(np.meshgrid)

 meshgrid(*xi, **kwargs)

Return coordinate matrices from coordinate vectors.

Make N-D coordinate arrays for vectorized evaluations of
N-D scalar/vector fields over N-D grids, given
one-dimensional coordinate arrays x1, x2,..., xn.

.. versionchanged:: 1.9
   1-D and 0-D cases are allowed.

Parameters
----------
x1, x2,..., xn : array_like
    1-D arrays representing the coordinates of a grid.
indexing : {'xy', 'ij'}, optional
    Cartesian ('xy', default) or matrix ('ij') indexing of output.
    See Notes for more details.

    .. versionadded:: 1.7.0
sparse : bool, optional
    If True a sparse grid is returned in order to conserve memory.
    Default is False.

    .. versionadded:: 1.7.0
copy : bool, optional
    If False, a view into the original arrays are returned in order to
    conserve memory.  Default is True.  Please note that
    ``sparse=False, copy=False`` will likely return non-contiguous
    arrays.  Furthermore, more than one element of a broadcast array
    may refe